### ISSUE TITLE
为什么我安装之后，登录提示这种错误呢？？

### ISSUE THREAD

**Issue by liujianfeng1020** [2017coding/BBS_admin#1]
Proxy error: Could not proxy request /api/user/login from localhost:2020 to http://localhost:1313/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

**Comment by liujianfeng1020** [comment]
是不是说你这个不包含本地服务器的代码？只是一个后台管理的界面。
服务器代码要链接到http://www.lyh.red:1313才行。
对吗？

**Comment by 2017coding** [comment]
是的，这个只是前端的代码，把代理的地址改成服务端地址就可以了

**Comment by 2017coding** [comment]
https://github.com/2017coding/BBS_node 服务端代码在这里
