### ISSUE TITLE
工作流模块是否开发？

### ISSUE THREAD

**Issue by xianzhiyun** [2017coding/BBS_admin#6]
大佬，什么时候开发工作流模块，或者有没有推荐得到库

**Comment by 2017coding** [comment]
这段时间离职找工作，暂不开发新功能。
工作流可以参考这个：https://github.com/huangxianyuan/hxyFrame

**Comment by william-xue** [comment]
迄今为止最优秀的admin 特别是二次封装的很牛逼

**Comment by william-xue** [comment]
"node-sass": "^4.9.0",
"sass-loader": "^7.1.0",这两个同时出现在生产和开发环境下

**Comment by 2017coding** [comment]
> "node-sass": "^4.9.0",
> "sass-loader": "^7.1.0",这两个同时出现在生产和开发环境下

是的，node-sass是这样安装的
